export const data = [
    {
        acquistion: "Social",
        visitor: 12,
        revisitor: 13,
        sessions: 14,
        bouncerate: 15,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
    {
        acquistion: "Search",
        visitor: 12,
        revisitor: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
    {
        acquistion: "Direct",
        visitor: 12,
        revisitor: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
    {
        acquistion: "Other",
        visitor: 12,
        revisitor: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
]

export const index = 0;
