export const dataTable = [
    {
        acquistion: "Social",
        users: 12,
        newusers: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
    {
        acquistion: "Search",
        users: 12,
        newusers: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
    {
        acquistion: "Direct",
        users: 12,
        newusers: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
    {
        acquistion: "Other",
        users: 12,
        newusers: 12,
        sessions: 12,
        bouncerate: 12,
        pagessession: 12,
        avgsessionduration: 12,
        conversionrate: 12,
        completion: 12,
        value: 12,
    },
]

export const index = 0;
